name: Nexus CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Show Python version
        run: python --version

      - name: Run demo_init.py
        run: python3 demo_init.py

      - name: Upload logs as artifact
        if: ${{ hashFiles('logs/demo_init.log') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: nexus-demo-logs
          path: logs/demo_init.log

